### ISSUE TITLE
agent2-perm.key warning on extension install

### ISSUE THREAD

**Issue by Radu3000** [greysonp/todomvc-extension#1]
Greyson,

I am getting this warning after following Build/Instructions steps...

This extension includes the key file 'C:\Projects\todomvc-extension-master\node_modules\karma\node_modules\http-proxy\test\fixtures\agent2-key.pem'. You probably don't want to do that.

I didn't see it before... I guess something must have changed.

Regards,
Radu

**Comment by greysonp** [comment]
Hi there,

If there's anything in the node_modules folder, it's nothing I can really do anything about. The `npm install` process is pulling code from other sources. In fact, the whole `package.json` (which declares which node modules to pull down) was not made by me, but instead by the maintainers of TodoMVC. Furthermore, the issue seems to be with the http-proxy module, so that's the real culprit here. 

I'll close this issue because there really isn't much I can do about it.
